name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake setup
      run: cmake -B build
    - name: cmake build
      run: cmake --build build
    - name: ctest
      run: cd build && ctest
